export const CQRS_MICROSERVICES_COMMAND: string = 'CQRS_MICROSERVICES_COMMAND';
export const CQRS_MICROSERVICES_EVENT: string = 'CQRS_MICROSERVICES_EVENT';
export const CQRS_MICROSERVICE_QUERY: string = 'CQRS_MICROSERVICE_QUERY';
