export const COMMAND_LISTENER_MESSAGE_PATTERN: string = 'CQRS_COMMAND_LISTENER';
export const EVENT_LISTENER_EVENT_PATTERN: string = 'CQRS_EVENT_LISTENER';
export const QUERY_LISTENER_MESSAGE_PATTERN: string = 'CQRS_QUERY_LISTENER';
